### ISSUE TITLE
Repository Status

### ISSUE THREAD

**Issue by JacobCallahan** [RedHatQE/polarizer#1]
Hey @Aftermath, we're checking in to see the status of this repository as part of an organization-level evaluation. Can you let us know the following?

1. Is this being actively developed/maintained?
2. Is this project in active use?
3. If not you, who is the primary contact for this project?

Thanks!

**Comment by jstavel** [comment]
hi @JacobCallahan this is another support library for a project polarizer-vertx. It is a service that is used by RHSMQE to send all test reports to Polarion. It is not used in any other project.

**Comment by JacobCallahan** [comment]
Thanks for the response!
